**Exploratory Data Analysis**

In [17]:
import pandas as pd
import openpyxl

data = pd.read_excel("data/Name - Address - NAICS Data.xlsx")
data.head()

,Index,kgupta@berkleymp.com,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220.0,Home Furnishing Merchant Wholesalers
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820.0,Public Relations Agencies
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320.0,"Promoters of Performing Arts, Sports, and Simi..."
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410.0,Drinking Places (Alcoholic Beverages)
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511.0,Full-Service Restaurants

In [18]:
print(f"Total {len(data)} examples")

Total 140776 examples

In [19]:
print("Counts per NAICS codes in dataset:")
data["NAICS Code"].value_counts()

Counts per NAICS codes in dataset:

NAICS Code
541611.0    5165
721110.0    4621
813990.0    4257
722511.0    3911
441110.0    2736
            ...
316992.0       1
486110.0       1
313320.0       1
112410.0       1
212392.0       1
Name: count, Length: 1066, dtype: int64

In [20]:
# Thre are 30,614 NaN Rows
data[data["NAICS Code"].isna()]

,Index,kgupta@berkleymp.com,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description
110162,113344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110163,113345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110164,113346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110165,113347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110166,113348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
140771,144448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140772,144449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140773,144450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140774,144451,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140775,144452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Looking at the most common NAICS codes
data[data["NAICS Code"] == 441110.0].head()

,Index,kgupta@berkleymp.com,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description
18,46,Gross Motors Inc,404 East Division Street,NaN,Neillsville,CLARK,WI,54456,441110.0,New Car Dealers
51,84,BOB HOWARD ENGLISH IMPORTS LLC,17970 Gulf Freeway,NaN,Friendswood,GALVESTON,TX,77546,441110.0,New Car Dealers
61,95,Keystone Chevrolet,8700 Charles Page Blvd,NaN,Sand Springs,TULSA,OK,74063,441110.0,New Car Dealers
177,223,"Saturn of Permian Basin, Inc. dba Mazda of Mid...",5115 West Loop 250 North,NaN,Midland,MIDLAND,TX,79707,441110.0,New Car Dealers
185,231,"Ram Motors Auto Sales, Inc.",4537 Arrowhead Ridge Dr SE,NaN,Rio Rancho,SANDOVAL,NM,87124,441110.0,New Car Dealers

Most common NAICS Codes:
1. Administrative Management and General Manageme...
2. Hotels (except Casino Hotels) and Motels
3. Other Similar Organizations (except Business, ...
4. Full-Service Restaurants
5. New Car Dealers

**Data Cleaning**

In [22]:
# Removing all rows with NaNs in NAICS Code
cleaned_data = data.dropna(subset=["NAICS Code"])

In [23]:
cleaned_data.head()

,Index,kgupta@berkleymp.com,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220.0,Home Furnishing Merchant Wholesalers
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820.0,Public Relations Agencies
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320.0,"Promoters of Performing Arts, Sports, and Simi..."
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410.0,Drinking Places (Alcoholic Beverages)
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511.0,Full-Service Restaurants

In [24]:
cleaned_data["INSURED_ST_CDE"].value_counts()

INSURED_ST_CDE
FL    10054
TX     9836
CA     7500
AL     4916
NY     4797
IL     4750
MA     4593
AZ     4486
GA     4163
NJ     4015
PA     3630
CT     3236
CO     3219
MI     2449
WA     2189
TN     2143
OH     2038
NC     1802
MO     1726
MD     1611
VA     1519
OR     1474
MS     1451
UT     1446
WI     1418
MN     1324
IN     1259
AR     1253
NE     1198
NV     1153
KS     1080
NM     1066
SC     1003
DE      931
ME      871
OK      859
ID      855
MT      854
NH      827
VT      663
IA      650
KY      570
RI      556
DC      503
HI      417
LA      409
WV      391
SD      387
WY      364
ND      181
AK       69
Mi        4
al        2
Ut        1
Tx        1
Name: count, dtype: int64

In [25]:
# Some state examples are lowercased
cleaned_data["INSURED_ST_CDE"] = cleaned_data["INSURED_ST_CDE"].str.upper()

In [26]:
cleaned_data["INSURED_ST_CDE"].value_counts()

INSURED_ST_CDE
FL    10054
TX     9837
CA     7500
AL     4918
NY     4797
IL     4750
MA     4593
AZ     4486
GA     4163
NJ     4015
PA     3630
CT     3236
CO     3219
MI     2453
WA     2189
TN     2143
OH     2038
NC     1802
MO     1726
MD     1611
VA     1519
OR     1474
MS     1451
UT     1447
WI     1418
MN     1324
IN     1259
AR     1253
NE     1198
NV     1153
KS     1080
NM     1066
SC     1003
DE      931
ME      871
OK      859
ID      855
MT      854
NH      827
VT      663
IA      650
KY      570
RI      556
DC      503
HI      417
LA      409
WV      391
SD      387
WY      364
ND      181
AK       69
Name: count, dtype: int64

In [27]:
# Renaming columns for consistency
cleaned_data = cleaned_data.rename(columns={"\xa0kgupta@berkleymp.com" : "Business_Name"})
cleaned_data = cleaned_data.rename(columns={"NAICS Code" : "NAICS_Code"})
cleaned_data = cleaned_data.rename(columns={"NAICS Description" : "NAICS_Description"})

In [28]:
cleaned_data.head()

,Index,Business_Name,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS_Code,NAICS_Description
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220.0,Home Furnishing Merchant Wholesalers
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820.0,Public Relations Agencies
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320.0,"Promoters of Performing Arts, Sports, and Simi..."
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410.0,Drinking Places (Alcoholic Beverages)
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511.0,Full-Service Restaurants

In [29]:
cleaned_data = cleaned_data.fillna('')

# Create the unified address column
cleaned_data['FULL_ADDRESS'] = (
    cleaned_data['INSURED_ADDR_LN_1'].str.strip() + ' ' + 
    cleaned_data['INSURED_ADDR_LN_2'].str.strip() + ', ' + 
    cleaned_data['INSURED_CTY_NM'].str.strip() + ', ' + 
    cleaned_data['INSURED_ST_CDE'].str.strip() + ' ' + 
    cleaned_data['INSURED_ZIP_CDE'].astype(str).str.strip()
)

# Clean up double commas if Address Line 2 was empty
cleaned_data['FULL_ADDRESS'] = cleaned_data['FULL_ADDRESS'].str.replace(', ,', ',').str.strip()
cleaned_data.head()

,Index,Business_Name,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS_Code,NAICS_Description,FULL_ADDRESS
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,,Irondale,JEFFERSON,AL,35210,423220.0,Home Furnishing Merchant Wholesalers,"1811 Crestwood Blvd , Irondale, AL 35210"
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820.0,Public Relations Agencies,"2213 Morris Ave 1st Floor, Birmingham, AL 35203"
2,24,"Transformus, LLC",4701 Brigadoon Dr,,Durham,DURHAM,NC,27705,711320.0,"Promoters of Performing Arts, Sports, and Simi...","4701 Brigadoon Dr , Durham, NC 27705"
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,,Chicago,COOK,IL,60632,722410.0,Drinking Places (Alcoholic Beverages),"3350 West 47th Street , Chicago, IL 60632"
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,,Chicago,COOK,IL,60632,722511.0,Full-Service Restaurants,"3350 West 47th Street , Chicago, IL 60632"

In [30]:
cleaned_data = cleaned_data.drop(columns=["Index", "INSURED_ADDR_LN_1", "INSURED_ADDR_LN_2", "INSURED_CTY_NM", "INSURED_CNTY_NM", "INSURED_ST_CDE", "INSURED_ZIP_CDE"])

In [31]:
cleaned_data.to_csv("data/cleaned_data.csv", index=False)

Prep for multi-head architecture

In [32]:
# Add input column for single encoder
cleaned_data['inputs'] = (
        "BUSINESS: " + cleaned_data['Business_Name'].astype(str) + 
        " | ADDRESS: " + cleaned_data['FULL_ADDRESS'].astype(str) + 
        " | DESC: " + cleaned_data['NAICS_Description'].fillna("").astype(str)
    )

In [33]:
# Ensure the column is string-type and padded (NAICS can sometimes lose leading zeros)
cleaned_data["NAICS_Code"] = cleaned_data["NAICS_Code"].astype(str).str.zfill(6)

# Extract the hierarchical levels
cleaned_data['sector_label'] = cleaned_data['NAICS_Code'].str[:2]    # 2-digit (e.g., 44)
cleaned_data['subsector_label'] = cleaned_data['NAICS_Code'].str[:3] # 3-digit (e.g., 441)
cleaned_data['industry_label'] = cleaned_data['NAICS_Code'].str[:6]          # 6-digit (e.g., 441320)

The following are the class counts used for the model arch

In [34]:
# Count number of unique codes at each level
print(f"Unique 2-digit sectors: {cleaned_data['sector_label'].nunique()}")
print(f"Unique 3-digit subsectors: {cleaned_data['subsector_label'].nunique()}")
print(f"Unique 6-digit industries: {cleaned_data['industry_label'].nunique()}")

Unique 2-digit sectors: 24
Unique 3-digit subsectors: 98
Unique 6-digit industries: 1066

In [35]:
from sklearn.model_selection import train_test_split

# Handle singletons (codes appearing only once)
counts = cleaned_data['NAICS_Code'].value_counts()
singletons = counts[counts == 1].index
df_multi = cleaned_data[~cleaned_data['NAICS_Code'].isin(singletons)]
df_single = cleaned_data[cleaned_data['NAICS_Code'].isin(singletons)]

# Split: Separate the 20% TEST set
# Remaining 80% will be used for Train + Val
train_val, test = train_test_split(
    df_multi, 
    test_size=0.20, 
    random_state=101, 
    stratify=df_multi['NAICS_Code']
)

# Second Split: Split the 80% into Train (70% total) and Val (10% total)
# Calculation: 0.10 / 0.80 = 0.125
train, val = train_test_split(
    train_val, 
    test_size=0.125, 
    random_state=101, 
    stratify=train_val['NAICS_Code']
)

# Add singletons to Training (They must be seen during training)
train = pd.concat([train, df_single])

print(f"Final Split Counts:\nTrain: {len(train)}\nVal: {len(val)}\nTest: {len(test)}")

Final Split Counts:
Train: 77129
Val: 11011
Test: 22022

In [36]:
train.to_csv("data/split_data/train.csv", index=False)
val.to_csv("data/split_data/val.csv", index=False)
test.to_csv("data/split_data/test.csv", index=False)