**Exploratory Data Analysis**

In [41]:
import pandas as pd
import openpyxl

data = pd.read_csv("data/NAICS_data_with_websites.csv")
data.head()

,Index,INSURED_NM,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description,Insured Website
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220,Home Furnishing Merchant Wholesalers,NaN
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820,Public Relations Agencies,NaN
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320,"Promoters of Performing Arts, Sports, and Simi...",NaN
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410,Drinking Places (Alcoholic Beverages),maddanthonysbar.com
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511,Full-Service Restaurants,maddanthonysbar.com

In [42]:
print(f"Total {len(data)} examples")

Total 110162 examples

In [43]:
print("Counts per NAICS codes in dataset:")
data["NAICS Code"].value_counts()

Counts per NAICS codes in dataset:

NAICS Code
541611    5165
721110    4621
813990    4257
722511    3911
441110    2736
          ...
316992       1
486110       1
313320       1
112410       1
212392       1
Name: count, Length: 1066, dtype: int64

In [44]:
# Thre are 30,614 NaN Rows
data[data["NAICS Code"].isna()]

Empty DataFrame
Columns: [Index, INSURED_NM, INSURED_ADDR_LN_1, INSURED_ADDR_LN_2, INSURED_CTY_NM, INSURED_CNTY_NM, INSURED_ST_CDE, INSURED_ZIP_CDE, NAICS Code, NAICS Description, Insured Website]
Index: []

In [45]:
# Looking at the most common NAICS codes
data[data["NAICS Code"] == 441110.0].head()

,Index,INSURED_NM,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description,Insured Website
18,46,Gross Motors Inc,404 East Division Street,NaN,Neillsville,CLARK,WI,54456,441110,New Car Dealers,www.grossauto.com
51,84,BOB HOWARD ENGLISH IMPORTS LLC,17970 Gulf Freeway,NaN,Friendswood,GALVESTON,TX,77546,441110,New Car Dealers,NaN
61,95,Keystone Chevrolet,8700 Charles Page Blvd,NaN,Sand Springs,TULSA,OK,74063,441110,New Car Dealers,keystonechevrolet.com
177,223,"Saturn of Permian Basin, Inc. dba Mazda of Mid...",5115 West Loop 250 North,NaN,Midland,MIDLAND,TX,79707,441110,New Car Dealers,www.mazdaofmidland.com
185,231,"Ram Motors Auto Sales, Inc.",4537 Arrowhead Ridge Dr SE,NaN,Rio Rancho,SANDOVAL,NM,87124,441110,New Car Dealers,rammotors.net

Most common NAICS Codes:
1. Administrative Management and General Manageme...
2. Hotels (except Casino Hotels) and Motels
3. Other Similar Organizations (except Business, ...
4. Full-Service Restaurants
5. New Car Dealers

**Data Cleaning**

In [46]:
# Removing all rows with NaNs in NAICS Code
cleaned_data = data.dropna(subset=["NAICS Code"])

In [47]:
cleaned_data.head()

,Index,INSURED_NM,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description,Insured Website
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220,Home Furnishing Merchant Wholesalers,NaN
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820,Public Relations Agencies,NaN
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320,"Promoters of Performing Arts, Sports, and Simi...",NaN
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410,Drinking Places (Alcoholic Beverages),maddanthonysbar.com
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511,Full-Service Restaurants,maddanthonysbar.com

In [48]:
cleaned_data["INSURED_ST_CDE"].value_counts()

INSURED_ST_CDE
FL    10054
TX     9836
CA     7500
AL     4916
NY     4797
IL     4750
MA     4593
AZ     4486
GA     4163
NJ     4015
PA     3630
CT     3236
CO     3219
MI     2449
WA     2189
TN     2143
OH     2038
NC     1802
MO     1726
MD     1611
VA     1519
OR     1474
MS     1451
UT     1446
WI     1418
MN     1324
IN     1259
AR     1253
NE     1198
NV     1153
KS     1080
NM     1066
SC     1003
DE      931
ME      871
OK      859
ID      855
MT      854
NH      827
VT      663
IA      650
KY      570
RI      556
DC      503
HI      417
LA      409
WV      391
SD      387
WY      364
ND      181
AK       69
Mi        4
al        2
Ut        1
Tx        1
Name: count, dtype: int64

In [49]:
# Some state examples are lowercased
cleaned_data["INSURED_ST_CDE"] = cleaned_data["INSURED_ST_CDE"].str.upper()

In [50]:
cleaned_data["INSURED_ST_CDE"].value_counts()

INSURED_ST_CDE
FL    10054
TX     9837
CA     7500
AL     4918
NY     4797
IL     4750
MA     4593
AZ     4486
GA     4163
NJ     4015
PA     3630
CT     3236
CO     3219
MI     2453
WA     2189
TN     2143
OH     2038
NC     1802
MO     1726
MD     1611
VA     1519
OR     1474
MS     1451
UT     1447
WI     1418
MN     1324
IN     1259
AR     1253
NE     1198
NV     1153
KS     1080
NM     1066
SC     1003
DE      931
ME      871
OK      859
ID      855
MT      854
NH      827
VT      663
IA      650
KY      570
RI      556
DC      503
HI      417
LA      409
WV      391
SD      387
WY      364
ND      181
AK       69
Name: count, dtype: int64

In [51]:
# Renaming columns for consistency
cleaned_data = cleaned_data.rename(columns={"INSURED_NM" : "Business_Name"})
cleaned_data = cleaned_data.rename(columns={"NAICS Code" : "NAICS_Code"})
cleaned_data = cleaned_data.rename(columns={"NAICS Description" : "NAICS_Description"})

In [52]:
cleaned_data.head()

,Index,Business_Name,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS_Code,NAICS_Description,Insured Website
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220,Home Furnishing Merchant Wholesalers,NaN
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820,Public Relations Agencies,NaN
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320,"Promoters of Performing Arts, Sports, and Simi...",NaN
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410,Drinking Places (Alcoholic Beverages),maddanthonysbar.com
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511,Full-Service Restaurants,maddanthonysbar.com

In [53]:
cleaned_data = cleaned_data.fillna('')

# Create the unified address column
cleaned_data['FULL_ADDRESS'] = (
    cleaned_data['INSURED_ADDR_LN_1'].str.strip() + ' ' + 
    cleaned_data['INSURED_ADDR_LN_2'].str.strip() + ', ' + 
    cleaned_data['INSURED_CTY_NM'].str.strip() + ', ' + 
    cleaned_data['INSURED_ST_CDE'].str.strip() + ' ' + 
    cleaned_data['INSURED_ZIP_CDE'].astype(str).str.strip()
)

# Clean up double commas if Address Line 2 was empty
cleaned_data['FULL_ADDRESS'] = cleaned_data['FULL_ADDRESS'].str.replace(', ,', ',').str.strip()
cleaned_data.head()

,Index,Business_Name,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS_Code,NAICS_Description,Insured Website,FULL_ADDRESS
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,,Irondale,JEFFERSON,AL,35210,423220,Home Furnishing Merchant Wholesalers,,"1811 Crestwood Blvd , Irondale, AL 35210"
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820,Public Relations Agencies,,"2213 Morris Ave 1st Floor, Birmingham, AL 35203"
2,24,"Transformus, LLC",4701 Brigadoon Dr,,Durham,DURHAM,NC,27705,711320,"Promoters of Performing Arts, Sports, and Simi...",,"4701 Brigadoon Dr , Durham, NC 27705"
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,,Chicago,COOK,IL,60632,722410,Drinking Places (Alcoholic Beverages),maddanthonysbar.com,"3350 West 47th Street , Chicago, IL 60632"
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,,Chicago,COOK,IL,60632,722511,Full-Service Restaurants,maddanthonysbar.com,"3350 West 47th Street , Chicago, IL 60632"

In [54]:
cleaned_data = cleaned_data.drop(columns=["Index", "INSURED_ADDR_LN_1", "INSURED_ADDR_LN_2", "INSURED_CTY_NM", "INSURED_CNTY_NM", "INSURED_ST_CDE", "INSURED_ZIP_CDE"])

In [55]:
cleaned_data.to_csv("data/cleaned_data.csv", index=False)

Prep for multi-head architecture

In [56]:
# Add input column for single encoder
cleaned_data['inputs'] = (
        "BUSINESS: " + cleaned_data['Business_Name'].astype(str) + 
        " | ADDRESS: " + cleaned_data['FULL_ADDRESS'].astype(str)
    )

In [57]:
# Ensure the column is string-type and padded (NAICS can sometimes lose leading zeros)
cleaned_data["NAICS_Code"] = cleaned_data["NAICS_Code"].astype(str).str.zfill(6)

# Extract the hierarchical levels
cleaned_data['sector_label'] = cleaned_data['NAICS_Code'].str[:2]    # 2-digit (e.g., 44)
cleaned_data['subsector_label'] = cleaned_data['NAICS_Code'].str[:3] # 3-digit (e.g., 441)
cleaned_data['industry_label'] = cleaned_data['NAICS_Code'].str[:6]          # 6-digit (e.g., 441320)

The following are the class counts used for the model arch

In [58]:
# Count number of unique codes at each level
print(f"Unique 2-digit sectors: {cleaned_data['sector_label'].nunique()}")
print(f"Unique 3-digit subsectors: {cleaned_data['subsector_label'].nunique()}")
print(f"Unique 6-digit industries: {cleaned_data['industry_label'].nunique()}")

Unique 2-digit sectors: 24
Unique 3-digit subsectors: 98
Unique 6-digit industries: 1066

In [59]:
from sklearn.model_selection import train_test_split

# Handle singletons (codes appearing only once)
counts = cleaned_data['NAICS_Code'].value_counts()
singletons = counts[counts == 1].index
df_multi = cleaned_data[~cleaned_data['NAICS_Code'].isin(singletons)]
df_single = cleaned_data[cleaned_data['NAICS_Code'].isin(singletons)]

# Split: Separate the 20% TEST set
# Remaining 80% will be used for Train + Val
train_val, test = train_test_split(
    df_multi, 
    test_size=0.20, 
    random_state=101, 
    stratify=df_multi['NAICS_Code']
)

# Second Split: Split the 80% into Train (70% total) and Val (10% total)
# Calculation: 0.10 / 0.80 = 0.125
train, val = train_test_split(
    train_val, 
    test_size=0.125, 
    random_state=101, 
    stratify=train_val['NAICS_Code']
)

# Add singletons to Training (They must be seen during training)
train = pd.concat([train, df_single])

print(f"Final Split Counts:\nTrain: {len(train)}\nVal: {len(val)}\nTest: {len(test)}")

Final Split Counts:
Train: 77129
Val: 11011
Test: 22022

In [60]:
train.to_csv("data/split_data/train.csv", index=False)
val.to_csv("data/split_data/val.csv", index=False)
test.to_csv("data/split_data/test.csv", index=False)

In [61]:
scraped = pd.read_csv("data/website_summaries.csv")
scraped.head(10)

,Index,INSURED_NM,INSURED_ADDR_LN_1,INSURED_ADDR_LN_2,INSURED_CTY_NM,INSURED_CNTY_NM,INSURED_ST_CDE,INSURED_ZIP_CDE,NAICS Code,NAICS Description,Insured Website,scraped_text,summary
0,20,"William Morris Home Fashions, Inc",1811 Crestwood Blvd,NaN,Irondale,JEFFERSON,AL,35210,423220,Home Furnishing Merchant Wholesalers,NaN,NaN,Insufficient content for summary.
1,21,"Alabama Policy Institute, Inc.",2213 Morris Ave,1st Floor,Birmingham,JEFFERSON,AL,35203,541820,Public Relations Agencies,NaN,NaN,Insufficient content for summary.
2,24,"Transformus, LLC",4701 Brigadoon Dr,NaN,Durham,DURHAM,NC,27705,711320,"Promoters of Performing Arts, Sports, and Simi...",NaN,NaN,Insufficient content for summary.
3,25,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722410,Drinking Places (Alcoholic Beverages),maddanthonysbar.com,NaN,Insufficient content for summary.
4,26,"Lacoco's Pizza & Pasta, Inc.",3350 West 47th Street,NaN,Chicago,COOK,IL,60632,722511,Full-Service Restaurants,maddanthonysbar.com,NaN,Insufficient content for summary.
5,27,"Henig Furs, Inc.",4135 Carmichael Road,NaN,Montgomery,MONTGOMERY,AL,36106,448190,Other Clothing Stores,https://www.henigfurs.com/,Layaway & Interest-Free Financing Options Avai...,Up to 80% off sitewide with extra 20% at check...
6,30,"Seoyon E-HWA Manufacturing Auburn, Inc.",217 Thweatt Industrial Blvd,NaN,Dadeville,TALLAPOOSA,AL,36853,336390,Other Motor Vehicle Parts Manufacturing,belite.co.kr,메뉴 바로가기 본문 바로가기 회사소개 회사개요 연혁 핵심가치 CSR ESG 정책 법...,Kwangsun Corporation operates globally with su...
7,31,"Seoyon E-HWA Manufacturing Auburn, Inc.",217 Thweatt Industrial Blvd,NaN,Dadeville,TALLAPOOSA,AL,36853,336112,Light Truck and Utility Vehicle Manufacturing,belite.co.kr,메뉴 바로가기 본문 바로가기 회사소개 회사개요 연혁 핵심가치 CSR ESG 정책 법...,Kwangsun Corporation operates global subsidiar...
8,33,Ian Garinger Consulting LLC,20 Pennbrook Ct,NaN,Boonton,MORRIS,NJ,7005,541512,Computer Systems Design Services,NaN,NaN,Insufficient content for summary.
9,34,Danson Construction LLC,2624 W Lone Cactus Drive,NaN,Phoenix,MARICOPA,AZ,85027,236220,Commercial and Institutional Building Construc...,dansonbldg.com,It’s our mission to make clients for life by u...,Danson Construction focuses on long-term clien...